version: '3.4'

services:
  eshopdb:
    image: postgres:17

  distributedcache:
    image: redis

  api:
    build:
      context: Bootstrapper/Api
      dockerfile: Dockerfile
  seq:
    image: datalust/seq:latest

volumes:
  postgres_eshopdb:
    